# PyTorch Tensors
- Tensors are a specialized data structure that are very similar to arrays and matrices.
- Tensors are used to **encode the inputs and outputs of a model** as well as **model parameters**.
- Tensors are similar to NumPy's `ndarray`s, but unlike ndarrays, tensors can be run on **GPUs** and other hardware accelerators.
- In fact, tensors and numpy arrays can **share the same memory** and eliminate the need for copying data.
- Tensors are **optimized for automatic differentiation** (`autograd`).

In [1]:
import torch
import numpy as np

## Initializing a Tensor

### Directly from data

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
?x_data

Type:        Tensor
String form:
tensor([[1, 2],
        [3, 4]])
Length:      2
File:        /opt/conda/lib/python3.8/site-packages/torch/__init__.py
Docstring:   <no docstring>

In [8]:
?torch.tensor

Docstring:
tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) -> Tensor

Constructs a tensor with no autograd history (also known as a "leaf tensor", see :doc:`/notes/autograd`) by copying :attr:`data`.

.. warning::

    When working with tensors prefer using :func:`torch.Tensor.clone`,
    :func:`torch.Tensor.detach`, and :func:`torch.Tensor.requires_grad_` for
    readability. Letting `t` be a tensor, ``torch.tensor(t)`` is equivalent to
    ``t.clone().detach()``, and ``torch.tensor(t, requires_grad=True)``
    is equivalent to ``t.clone().detach().requires_grad_(True)``.

.. seealso::

    :func:`torch.as_tensor` preserves autograd history and avoids copies where possible.
    :func:`torch.from_numpy` creates a tensor that shares storage with a NumPy array.

Args:
    data (array_like): Initial data for the tensor. Can be a list, tuple,
        NumPy ``ndarray``, scalar, and other types.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the de

### From Numpy Array

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
np_array

array([[1, 2],
       [3, 4]])

### From another tensor

In [8]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0251, 0.7155],
        [0.2948, 0.5701]]) 



### With random or constant values

In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5083, 0.3371, 0.8856],
        [0.2167, 0.2616, 0.2405]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of Tensor

In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [11]:
tensor

tensor([[0.7373, 0.5433, 0.4738, 0.3904],
        [0.1637, 0.7357, 0.5085, 0.7052],
        [0.1745, 0.1713, 0.7077, 0.2926]])

In [12]:
tensor2 = torch.tensor(tensor, device='cuda:2')
tensor2

/tmp/ipykernel_71/1445035615.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor2 = torch.tensor(tensor, device='cuda:2')


tensor([[0.7373, 0.5433, 0.4738, 0.3904],
        [0.1637, 0.7357, 0.5085, 0.7052],
        [0.1745, 0.1713, 0.7077, 0.2926]], device='cuda:2')

In [13]:
tensor2.shape

torch.Size([3, 4])

In [14]:
tensor2.dtype

torch.float32

## Operations on Tensors

There are over 100 tensor operations:
- creation
  - `tensor, sparse_coo_tensor, asarry, as_tensor, as_strided, from_numpy, from_dlpack, frombuffer, zeros, zeros_like, ones, ones_like, arange, range, linspace, logspace, eye, empty, empty_like, empty_strided, full, full_like, quantize_per_tensor, quantize_per_channel, dequantize, complex, polar, heaviside`
- indexing, slicing, joining, mutating
  - `adjoint, argwhere, cat, concat, concatenate, conj, chunk, dsplit, column_stack, dstack, gather, hsplit, hstack, index_add, index_copy, index_reduce, index_select, masked_select, movedim, moveaxis, narrow, nonzero, permute, reshape, row_stack, select, scatter, diagonal_scatter, slice_scatter, scatter_add, scatter_reduce, split, squeeze, stack, swapaxes, swapdims, t, take, take_along_dim, tensor_split, tile, traspose, unbind, unsqueeze, vsplit, vstack, where`
- `Generator`
- random sampling
  - `seed, manual_seed, initial_seed, get_rng_state, set_rng_state, bernoulli, multinomial, normal, poisson, rand, rand_like, randint, randint_like, randn, randn_like, randperm`
- serialization
  - `save, load`
- parallelism
  - `get_num_threads, set_num_threads, get_num_interop_threads, set_num_interop_threads`
- gradient computation
  - `no_grad, enable_grad, set_grad_enabled, is_grad_enabled, inference_mode, is_inference_mode_enabled`
- math pointwise
  - `abs, absolute, acos, arccos, acosh, arccosh, add, addcdiv, addcmul, angle, asin, arcsin, asinh, arcsinh, atan, arctan, atanh, arctanh, atan2, arctan2, bitwise_not, bitwise_and, bitwise_or, bitwise_xor, bitwise_left_shift, bitwise_right_shift, ceil, clamp, clip, conj_physical, copysign, cos, cosh, deg2rad, div, divide, digamma, erf, erfc, erfinv, exp, exp2, expm1, fake_quantize_per_channel_affine, fake_quantize_per_tensor_affine, fix, float_power, floor, floor_divide, fmod, frac, frexp, gradient, imag, ldexp, lerp, lgamma, log, log10, log1p, log2, logaddexp2, logical_and, logical_not, logical_or, logical_xor, logit, hypot, i0, igamma, igammac, mul, multiply, mvlgamma, nan_to_num, neg, negative, nextafer, polygamma, positive, pow, quantized_batch_norm, quantized_max_pool1d, quantized_max_pool2d, rad2deg, real, reciprocal, remainder, round, rsqrt, sigmoid, sign, sgn, signbit, sin, sinc, sinh, sqrt, square, sub, subtract, tan, tanh, true_divide, trunc, xlogy`
- reduction
  - `argmax, argmin, amax, amin, aminmax, all, any, max, min, dist, logsumexp, mean, nanmean, median, nanmedian, mode, norm, nansum, prod, quantile, nanquantile, std, std_mean, sum, unique, unique_consecutive, var, var_mean, count_nonzero`
- comparison
  - `allclose, argsort, eq, qual, ge, greater_equal, gt, greater, isclose, isfinite, isin, isinf, isposinf, isneginf, isnan, isreal, kthvalue, le, less_equal, lt, less, maximum, minimum, fmax, fmin, ne, not_equal, sort, topk, msort`
- spectral
  - `stft, istft, bartlett_window, blackman_window, hamming_window, hann_window, kaiser_window`
- other ops
  - `atleast_1d, atleast_2d, atleast_3d, bincount, block_diag, broadcast_tensors, broadcast_to, broacast_shapes, bucketize, cartesian_prod, cdist, clone, combinations, corrcoef, cov, cross, cummax, cummin, cumprod, cumsum, diag, diag_embed, diagflat, diagonal, diff, einsum, flatten, flip, fliplr, flipup, kron, rot90, gcd, histc, histogram, histogramdd, meshgrid, lcm, logcumsumexp, ravel, renorm, repeat_interleave, roll, searchsorted, tensordot, trace, tril, tril_indices, triu, triu_indices, unflatten, vander, view_as_real, view_as_complex, resolve_conj, resolve_neg`
- BLAS, LAPACK
  - `addbmm, addmm, addmv, addr, baddbmm, bmm, chain_matmul, cholesky, cholesky_inverse, cholesky_solve, dot, geqrf, ger, inner, inverse, det, logdet, slogdet, lu, lu_solve, lu_unpack, matmul, matrix_power, matrix_exp, mm, mv, orgqr, ormqr, outer, pinverse, qr, svd, svd_lowrank, pca_lowrank, symeig, logpcg, trapz, trapezoid, cumulative_trapezoid, triangular_solve, vdot`
- utilities
  - `compiled_with_cxx11_abi, result_type, can_cast, promote_types, use_deterministic_algorithms, are_deterministic_algorithms_enabled, is_deterministic_algorithms_warn_only_enabled, set_deterministic_debug_mode, get_deterministic_debug_mode, set_float32_matmul_precision, get_float32_matmul_precision, set_warn_always, is_warn_always_enabled, _assert`

Each operation can run on GPU. By default, tensors are created on the CPU. Need to explicitly move tensors to GPU using `.to` method.

In [ ]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [17]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)
print(f'Last row: {tensor[-1]}')
print(f'Last column: {tensor[..., -1]}')

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
Last row: tensor([1., 0., 1., 1.])
Last column: tensor([1., 1., 1., 1.])


In [18]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [19]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]], device='cuda:0')


In [20]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0')

In [21]:
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0')

In [22]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')

In [23]:
y3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0')

In [24]:
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0')

In [25]:
torch.rand_like(y1)

tensor([[0.5108, 0.7833, 0.0190, 0.5554],
        [0.8312, 0.7484, 0.9300, 0.7997],
        [0.2769, 0.7811, 0.6711, 0.5448],
        [0.5352, 0.4821, 0.6399, 0.6909]], device='cuda:0')

**Single-element tensors** can be converted to Python value using `.item()`

In [28]:
agg = tensor.sum()
print(agg.item(), type(agg.item()))

12.0 <class 'float'>


In [27]:
agg

tensor(12., device='cuda:0')

**In-place operations** replace operands with results, and denoted with postfix `_`.

In [29]:
print(f'{tensor}\n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]], device='cuda:0')


In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.